services:
  # 1. BASE DE DONNÉES
  db:
    image: postgres:15
    container_name: odoo_db_23V2283  # Nom unique pour éviter les conflits
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - odoo_network
    restart: unless-stopped

  # 2. APPLICATION ODOO
  odoo:
    image: odoo:17
    container_name: odoo_app_23V2283 # Nom unique
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=${DB_PASSWORD}
      - EMAIL_HOST=${SMTP_SERVER}
      - EMAIL_PORT=${SMTP_PORT}
      - EMAIL_HOST_USER=${SMTP_USER}
      - EMAIL_HOST_PASSWORD=${SMTP_PASSWORD}
      - EMAIL_USE_TLS=True
    volumes:
      - ./odoo_app/config:/etc/odoo
      - ./odoo_app/addons:/mnt/extra-addons
      - ./odoo_app/data:/var/lib/odoo
    networks:
      - odoo_network
    restart: unless-stopped

  # 3. PROXY NGINX
  nginx:
    image: nginx:alpine
    container_name: odoo_nginx_23V2283 # Nom unique
    depends_on:
      - odoo
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/nginx/ssl
    ports:
      - "5880:443"  # On envoie le 5880 vers le port SSL (443)
    #  - "80:80" 
    networks:
      - odoo_network
    restart: unless-stopped

  # 4. CERTBOT
  certbot:
    image: certbot/certbot
    container_name: odoo_certbot_23V2283
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    command: certonly --webroot -w /var/www/certbot --email ${CERTBOT_EMAIL} -d ${DOMAIN} --agree-tos --non-interactive --force-renewal
    networks:
      - odoo_network

networks:
  odoo_network:
    driver: bridge